project:
  name: "enjoy-research-app"
  mode: "dev"
  port: 8080
log:
  level: "debug"
  filename: "enjoy-research-app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "8.130.137.7"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "enjoy_research_app"
  max_open_conns: 200
  max_idle_conns: 50


